---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: kafkaconnect
spec:
  lookupPolicy:
    local: false
---
kind: KafkaConnect
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: kafkaconnect
  namespace: ibmmq
  annotations:
    strimzi.io/use-connector-resources: 'true'
spec:
  version: 3.5.1
  replicas: 1
  bootstrapServers: 'kafka-kafka-bootstrap:9093'
  tls:
    trustedCertificates:
      - secretName: kafka-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  build: 
    output:
      image: 'kafkaconnect:1.0'
      type: imagestream
    plugins: 
      - name: mq-source
        artifacts:
          - type: jar
            url: https://github.com/ibm-messaging/kafka-connect-mq-sink/releases/download/v1.5.0/kafka-connect-mq-sink-1.5.0-jar-with-dependencies.jar
      - name: mq-sink
        artifacts:
          - type: jar
            url: https://github.com/ibm-messaging/kafka-connect-mq-source/releases/download/v1.3.3/kafka-connect-mq-source-1.3.3-jar-with-dependencies.jar
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: mq-source
  labels:
    strimzi.io/cluster: kafkaconnect
spec:
  class: com.ibm.eventstreams.connect.mqsource.MQSourceConnector
  tasksMax: 1
  config:
    topic: mq-source
    mq.queue.manager: QM1
    mq.connection.name.list: ibmmq(1414)
    mq.channel.name: DEV.APP.SVRCONN
    mq.queue: DEV.QUEUE.1
    mq.record.builder: com.ibm.eventstreams.connect.mqsource.builders.DefaultRecordBuilder
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    mq.user.name: app
    mq.password: passw0rd
    mq.message.body.jms: true
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: mq-sink
  labels:
    strimzi.io/cluster: kafkaconnect
spec:
  class: com.ibm.eventstreams.connect.mqsink.MQSinkConnector
  tasksMax: 1
  config:
    topics: mq-source
    mq.queue.manager: QM1
    mq.connection.name.list: ibmmq(1414)
    mq.channel.name: DEV.APP.SVRCONN
    mq.queue: DEV.QUEUE.2
    mq.message.builder: com.ibm.eventstreams.connect.mqsink.builders.DefaultMessageBuilder
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    mq.user.name: app
    mq.password: passw0rd
