version: '2'

services:

  zookeeper:
    image: quay.io/strimzi/kafka:0.36.0-kafka-3.5.0
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
      ]
    ports:
    - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: quay.io/strimzi/kafka:0.36.0-kafka-3.5.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  mq:
    image: icr.io/ibm-messaging/mq:latest
    ports:
    - "1414:1414"
    - "9443:9443"
    environment:
      LICENSE: accept 
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: passw0rd

  mq-source:
    image: quay.io/giovanni_savino_it/kafkaconnect-with-mq-source-sink:1.0
    ports:
    - "8083:8083"
    volumes:
      - ${PWD}/config:/opt/kafka/config
  samplemqquarkusapp:
    image: quay.io/giovanni_savino_it/samplemqquarkusapp:1.0
    ports:
    - "8080:8080"
    environment:
      HOST: "mq"